#!/bin/bash
#     This file is part of scallop.
#
#	 scallop is free software: you can redistribute it and/or modify
#	 it under the terms of the GNU General Public License as published by
#	 the Free Software Foundation, either version 3 of the License, or
#	 (at your option) any later version.
#	
#	 scallop is distributed in the hope that it will be useful,
#	 but WITHOUT ANY WARRANTY; without even the implied warranty of
#	 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	 GNU General Public License for more details.
#	
#	 You should have received a copy of the GNU General Public License
#	 along with scallop.  If not, see <http://www.gnu.org/licenses/>.
#	
#	 Created on: Nov 15, 2014
#     		Author: Andreas Linscheid
#
#
#	This script generates main.cpp in each of the <modules>/test/ folders if Test.h exists.
#	The main routine will include Test.h and declare an object of type test. Then it
#		it will run the run_test() method that should call all tests in the module.
#	It further generates a minimal Makefile to compile and run each module test.
#
newline=$'\n'
tab=$'\t'
testFolders=`find ../scallop/ -type d | grep -P "\/test$"`
includes=""
executionLines=""
for i  in $testFolders; do
	moduleRelPath=${i%%"/test"}
	module=${moduleRelPath##"../scallop/"}
	if [[ -f "$i/Test.h" ]]; then
		include=`echo -e "#include \"scallop/$module/test/Test.h\""`
		declaretion=`echo -e "scallop::$module::test::Test $module""_test;"`	
		execution=`echo -e "$module""_test.run_test();"`
		execution=${newline}${newline}${tab}"//Test of the module $module"${newline}${tab}${declaretion}${newline}${tab}${execution}
		#
		#	generate the final cpp file
		#
		timestamp=`date`
		cat > $i/tests.cpp <<- EOF
		/*
		 * This file is part of scallop.
		 * 
		 * tests.cpp
		 *  
		 *  Tests the $module module of scallop
		 *
		 *  Generated by create_local_tests.sh
		 *  DO NOT MODIFY - ALL CHANGES WILL BE LOST
		 *  
		 *  Time where this file was generated is $timestamp
		 */
		
		#include <iostream>
		$includes
		
		int main (int argc, char *argv[]){
			${tab}std::cout << "Starting test of the $module module of scallop: \\n\\n" << std::endl;
			${tab}std::cout << "\\tThe test was generated at $timestamp" << std::endl;
			${tab}$execution
			
			
			${tab}std::cout << "\\n\\nTest finished" << std::endl;
			${tab}return 0;
		}
		EOF
	else
		echo -e "\n WARNING:"
		echo -e "Could not find tests for module $module\n"
	fi
done

