/*
 * This file is part of scallop.
 * 
 * tests.cpp
 *  
 *  Tests the input module of scallop
 *
 *  Generated by create_local_tests.sh
 *  DO NOT MODIFY - ALL CHANGES WILL BE LOST
 *  
 *  Time where this file was generated is Tue Nov 25 18:12:58 CET 2014
 */

#include <iostream>


int main (int argc, char *argv[]){
	std::cout << "Starting test of the input module of scallop: \n\n" << std::endl;
	std::cout << "\tThe test was generated at Tue Nov 25 18:12:58 CET 2014" << std::endl;
	

	//Test of the module input
	scallop::input::test::Test input_test;
	input_test.run_test();


	std::cout << "\n\nTest finished" << std::endl;
	return 0;
}
